export enum SummarySendingPolicy {

    ALWAYS = "ALWAYS",
    NEVER = "NEVER",
    IF_CONTAINS_NON_PASSED = "IF_CONTAINS_NON_PASSED",
    IF_CONTAINS_UNKNOWN_ISSUES = "IF_CONTAINS_UNKNOWN_ISSUES"

}
